version: '3.1'

services:
    mysqldb:
        image: mysql/mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: Contra1234.
            MYSQL_DATABASE: itzgiodb
            MYSQL_USER: giorgio
            MYSQL_PASSWORD: Contra1234.
            MYSQL_ROOT_HOST: 172.17.0.1
        ports:
            - 3306:3306
    postgresdb:
        build: ./postgresdb
        environment:
            POSTGRES_PASSWORD: Contra1234.
            POSTGRES_USER: giorgio
            POSTGRES_DB: itzgiodb
        ports:
            - 5432:5432
    webserver:
        build: ./webserver
        ports:
            - 80:8080
        links:
            - postgresdb
            - mysqldb
        volumes:
            - ./webserver/app:/src
